#!/usr/bin/env python3
"""Check every seeded board token and report which still resolve.

Board tokens rot — companies migrate ATS, rename, or go private. Run this
before loading the seed, and again whenever Scout starts reporting source
errors:

    python db/seeds/verify_boards.py                 # report only
    python db/seeds/verify_boards.py --prune         # rewrite the JSON
    python db/seeds/verify_boards.py --sql > seed.sql
"""
from __future__ import annotations

import argparse
import asyncio
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "api"))

import httpx  # noqa: E402

from app.agents.scout.ats import build_ats_source  # noqa: E402

SEED = pathlib.Path(__file__).with_name("company_boards.json")
UA = "job-agent/0.1 (board token verification; personal job search)"


async def check(board: dict, client: httpx.AsyncClient) -> tuple[dict, int, str]:
    source = build_ats_source(board["kind"], board["slug"], board.get("company_name"))
    try:
        jobs = await source.fetch(client)
    except httpx.ProxyError as exc:
        # A corporate or sandbox egress policy refusing CONNECT says nothing
        # about the board. Reporting it as dead would prune a good token.
        return board, -1, f"BLOCKED {exc}"[:80]
    except httpx.HTTPStatusError as exc:
        status = exc.response.status_code
        if status in (403, 407) and "proxy" in exc.response.text.lower():
            return board, -1, f"BLOCKED HTTP {status}"
        return board, -1, f"HTTP {status}"
    except Exception as exc:
        return board, -1, f"{type(exc).__name__}: {exc}"[:80]
    return board, len(jobs), "ok"


async def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prune", action="store_true", help="drop boards that do not resolve")
    parser.add_argument("--sql", action="store_true", help="emit INSERT statements for live boards")
    parser.add_argument("--concurrency", type=int, default=6)
    args = parser.parse_args()

    data = json.loads(SEED.read_text())
    boards = data["boards"]
    semaphore = asyncio.Semaphore(args.concurrency)

    async with httpx.AsyncClient(
        timeout=20.0, follow_redirects=True, headers={"User-Agent": UA}
    ) as client:

        async def guarded(board):
            async with semaphore:
                return await check(board, client)

        results = await asyncio.gather(*(guarded(b) for b in boards))

    live = [(b, n) for b, n, status in results if status == "ok" and n > 0]
    empty = [(b, n) for b, n, status in results if status == "ok" and n == 0]
    blocked = [(b, note) for b, _, note in results if note.startswith("BLOCKED")]
    dead = [(b, note) for b, _, note in results if note != "ok" and not note.startswith("BLOCKED")]

    if blocked and not live:
        print(
            "Every board was refused by the egress proxy, so none of this is a verdict on "
            "the tokens.\nRun this from a network that can reach the ATS hosts before "
            "trusting the output.",
            file=sys.stderr,
        )

    if args.sql:
        if blocked:
            print(
                "-- Refusing to emit SQL: some boards could not be reached "
                "(network policy), so the 'live' set is incomplete.",
                file=sys.stderr,
            )
            return 2
        print("-- Generated by db/seeds/verify_boards.py; only verified boards.")
        print("insert into source_seeds (kind, slug, company_name) values")
        rows = [
            f"  ('{b['kind']}', '{b['slug']}', '{b['company_name'].replace(chr(39), chr(39) * 2)}')"
            for b, _ in live
        ]
        print(",\n".join(rows))
        print("on conflict (kind, slug) do nothing;")
        return 0

    for board, count in sorted(live, key=lambda r: -r[1]):
        print(f"  ok    {board['kind']:16} {board['slug']:20} {count:4d} postings")
    for board, _ in empty:
        print(f"  empty {board['kind']:16} {board['slug']:20}    0 postings (kept)")
    for board, note in blocked:
        print(f"  ?     {board['kind']:16} {board['slug']:20} unreachable — {note}")
    for board, note in dead:
        print(f"  DEAD  {board['kind']:16} {board['slug']:20} {note}")

    print(
        f"\n{len(live)} live, {len(empty)} empty, {len(dead)} dead, "
        f"{len(blocked)} unverifiable, {len(boards)} total"
    )

    if args.prune and blocked:
        print(
            f"refusing to prune: {len(blocked)} boards were unreachable, so a dead "
            "verdict cannot be distinguished from a blocked one",
            file=sys.stderr,
        )
        return 2

    if args.prune and dead:
        keep = {(b["kind"], b["slug"]) for b, _ in live + empty}
        data["boards"] = [b for b in boards if (b["kind"], b["slug"]) in keep]
        SEED.write_text(json.dumps(data, indent=2) + "\n")
        print(f"pruned {len(dead)} dead boards from {SEED.name}")

    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
